import { existsSync, mkdirSync } from 'node:fs';
import { dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import Database from 'better-sqlite3';
import { drizzle } from 'drizzle-orm/better-sqlite3';
import { migrate } from 'drizzle-orm/better-sqlite3/migrator';
import * as schema from './schema.js';

/**
 * A Drizzle database handle bound to our schema. Derived from `drizzle()`'s
 * return type so it includes `$client` (the underlying better-sqlite3
 * connection, used to `.close()` in tests) — the `BetterSQLite3Database` class
 * alone does not expose it.
 */
export type AppDatabase = ReturnType<typeof drizzle<typeof schema>>;

export interface OpenDatabaseOptions {
  databasePath: string;
}

// Migrations generated by `drizzle-kit generate` from schema.ts. Resolved
// relative to this module so it works under tsx, compiled dist, and vitest.
const MIGRATIONS_FOLDER = fileURLToPath(new URL('../drizzle', import.meta.url));

/**
 * Opens a SQLite database at the given path (creating parent directories as
 * needed) and brings its schema up to date by running the Drizzle migrations.
 * Pass ':memory:' for ephemeral, test-isolated databases.
 */
export function openDatabase({ databasePath }: OpenDatabaseOptions): AppDatabase {
  if (databasePath !== ':memory:') {
    const directory = dirname(databasePath);
    if (!existsSync(directory)) {
      mkdirSync(directory, { recursive: true });
    }
  }

  const sqlite = new Database(databasePath);
  sqlite.pragma('journal_mode = WAL');

  const database = drizzle(sqlite, { schema });
  migrate(database, { migrationsFolder: MIGRATIONS_FOLDER });
  return database;
}
